# Generated by Django 5.0.7 on 2025-07-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_despesa_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='parcela_atual',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
