# Generated by Django 5.2.4 on 2025-07-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_despesa_parcela_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='tema_escuro',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='icones_coloridos',
            field=models.BooleanField(default=False, verbose_name='Ícones Coloridos'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='dashboard_tema',
            field=models.CharField(choices=[('corona-dark', 'Corona Dark'), ('vanta-dark', 'Vanta Dark'), ('futureui-color', 'Future UI Colorido'), ('material-light', 'Material Light')], default='corona-dark', max_length=30),
        ),
    ]
