# Generated by Django 5.2.4 on 2025-07-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_configuracao_tema_escuro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='icones_coloridos_telas',
            field=models.BooleanField(default=False, verbose_name='Ícones Coloridos (Telas do Sistema)'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='icones_coloridos',
            field=models.BooleanField(default=False, verbose_name='Ícones Coloridos (Menu Lateral)'),
        ),
    ]
