# Generated by Django 5.2.4 on 2025-07-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_configuracao_icones_coloridos_telas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='icones_coloridos_telas',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='escala_interface',
            field=models.PositiveIntegerField(choices=[(100, '100% (Padrão)'), (90, '90%'), (80, '80%')], default=100, verbose_name='Escala da Interface (%)'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='dashboard_tema',
            field=models.CharField(choices=[('corona-dark', 'Corona Dark'), ('vanta-dark', 'Vanta Dark'), ('futureui-color', 'Future UI Colorido'), ('material-light', 'Material Light'), ('sgfp-light-sidebar', 'SGFP Light Sidebar')], default='corona-dark', max_length=30),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='icones_coloridos',
            field=models.BooleanField(default=False, verbose_name='Ícones Coloridos'),
        ),
    ]
