# Generated by Django 5.2.4 on 2025-07-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_configuracao_icones_coloridos_telas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='escala_interface',
            field=models.PositiveIntegerField(choices=[(100, '100% (Padrão)'), (95, '95%'), (90, '90%'), (85, '85%'), (80, '80%'), (75, '75%'), (70, '70%'), (65, '65%'), (60, '60%')], default=100, verbose_name='Escala da Interface (%)'),
        ),
    ]
