# Generated by Django 5.2.4 on 2025-07-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_configuracao_escala_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='escala_interface',
            field=models.PositiveIntegerField(choices=[(100, '100% (Padrão)'), (95, '95%'), (90, '90%'), (85, '85%'), (80, '80%'), (75, '75%'), (70, '70%'), (65, '65%'), (60, '60%'), (55, '55%'), (50, '50%'), (45, '45%'), (40, '40%'), (35, '35%'), (30, '30%')], default=100, verbose_name='Escala da Interface (%)'),
        ),
    ]
