# Generated by Django 5.0.7 on 2025-07-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_configuracao_escala_interface'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatura',
            options={'ordering': ['-vencimento']},
        ),
        migrations.AlterUniqueTogether(
            name='fatura',
            unique_together={('cartao', 'vencimento')},
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='escala_interface',
            field=models.PositiveIntegerField(choices=[(70, '70%'), (80, '80%'), (90, '90%'), (100, '100% (Padrão)'), (110, '110%'), (120, '120%'), (130, '130%')], default=100, verbose_name='Escala da Interface (%)'),
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='mes',
        ),
    ]
